# Generated by Django 5.1 on 2024-11-17 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colecao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='colecoes_auth_User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colecao',
            name='colecionador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecoes_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
