# Generated by Django 5.1 on 2024-11-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_colecao_owner_alter_colecao_colecionador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nome',
            new_name='name',
        ),
    ]
